Remove unused `contrib/experiments/cursesio.py`
This imports `curses.wrapper`, which fails on my system:

```
python contrib/experiments/cursesio.py
Traceback (most recent call last):
  File "/home/dmr/workspace/synapse/contrib/experiments/cursesio.py", line 16, in <module>
    import curses.wrapper
ModuleNotFoundError: No module named 'curses.wrapper'
```

I'm guessing that this used to work under Python 2, but nobody has used
it since. Assuming it is long dead, I propose removing it.