Plaster around KeyError in `_get_state_map_for_room`.
When adding a `on_new_event` handler on a federated homeserver, I keep hitting:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 285, in _unsafe_process_queue
    await self._process_command(cmd, conn, stream_name)
  File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 300, in _process_command
    await self._process_rdata(stream_name, conn, cmd)
  File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 516, in _process_rdata
    await self.on_rdata(stream_name, cmd.instance_name, cmd.token, rows)
  File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 531, in on_rdata
    await self._replication_data_handler.on_rdata(
  File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/client.py", line 212, in on_rdata
    await self.notifier.on_new_room_event_args(
  File "/usr/local/lib/python3.9/site-packages/synapse/notifier.py", line 338, in on_new_room_event_args
    await self._third_party_rules.on_new_event(event_id)
  File "/usr/local/lib/python3.9/site-packages/synapse/events/third_party_rules.py", line 399, in on_new_event
    state_events = await self._get_state_map_for_room(event.room_id)
  File "/usr/local/lib/python3.9/site-packages/synapse/events/third_party_rules.py", line 471, in _get_state_map_for_room
    state_events[key] = room_state_events[event_id]
KeyError: (some event id)
```

I do not understand how we can reach such a state. However, a few clues:

- I can reproduce on a live server with an event was sent back in last May;
- according to my logs, the code never actually calls my `on_new_event` callback, so it's probably not guilty;
- this exception is risen on a codepath that is deactivated when there are no `on_new_event` callbacks, so there is a possibility that the error is simply activated by the existence of the `on_new_event` handler.

This PR simply plasters around the error by ignoring events that do not show up in the state.