Also bump click
Without this, pip complains:

```
ERROR: Cannot install black==22.3.0 and matrix-synapse[dev]==1.55.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    matrix-synapse[dev] 1.55.2 depends on click==7.1.2; extra == "dev"
    black 22.3.0 depends on click>=8.0.0
```