Update sentry-sdk
This suppresses the complaint

```
synapse/app/_base.py:491: error: Cannot instantiate abstract class "init" with abstract attribute "__exit__"  [abstract]
```

by including the change in
https://github.com/getsentry/sentry-python/p

I can't see anything obviously terrible in the changelogs; see
https://github.com/getsentry/sentry-python/releases

Additionally, we don't upper bound sentry-sdk, so fresh installations
might be using this version anyway.